author: ustwo Fampany Ltd.
author_url: https://ustwo.com/
github_url: https://github.com/ustwo/baseviewcontroller-swift
module: BaseViewControllerSwift
output: docs
theme: fullwidth
xcodebuild_arguments:
  [
    -workspace,
    "BaseViewControllerSwift.xcworkspace",
    -scheme,
    "BaseViewControllerSwift",
  ]
