disabled_rules:
  - line_length
  - nesting
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - file_header
  - first_where
  - force_unwrapping
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

included:
  - Example
  - Sources
excluded:
  - Pods
  - Tests

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  BaseViewControllerSwift
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} ustwo Fampany Ltd\. All rights reserved\.
                    \/\/

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
vertical_whitespace:
  max_empty_lines: 2

custom_rules:
  # pragma mark style
  marks_empty_space:
    name: "Marks"
    regex: "(//MARK)"
    message: "There should be an empty space between // and the MARK."
    severity: warning

  marks_style:
    name: "Marks"
    regex: "(// MARK: -?[a-zA-Z0-9])"
    message: "Marks should follow the following structure: // MARK: - Comment."
    severity: warning

  # comments style
  comments_empty_space:
    name: "Comments"
    regex: "(//[a-zA-Z0-9])"
    match_kinds:
      - comment
    message: "There should be an empty space between // and the comment."
    severity: warning

  comments_empty_line_after:
    name: "Comments"
    regex: "([^\n]\n^ *[a-zA-Z0-9{])"
    match_kinds:
      - comment
    message: "There should be an empty line after a comment."
    severity: warning
