osx_image: xcode11.1
language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
  - rvm list
  - rvm install $(cat .ruby-version)
  - rvm use $(cat .ruby-version)
  - gem update --system
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

install:
  - bundle install --without development

env:
  - SIM_PLATFORM="iOS Simulator" SIM_DEVICE="iPhone 11"
  - SIM_PLATFORM="tvOS Simulator" SIM_DEVICE="Apple TV"
script:
  - ./fastlane/travis.sh

jobs:
  include:
    - stage: "App Test"
      env: SIM_PLATFORM="iOS Simulator" SIM_DEVICE="iPhone 11"
      script:
        - ./fastlane/build_test.sh
    - stage: "Pod Validation"
      env: SIM_PLATFORM="iOS Simulator" SIM_DEVICE="iPhone 11"
      script:
        - "bundle exec pod lib lint"
