osx_image: xcode8.3
language: objective-c

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
script:
- "./fastlane/travis.sh"
