osx_image: xcode11
language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
  - rvm list
  - rvm install $(cat .ruby-version)
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install bundler -v 2.0.2

# Test using Fastlane
script:
  - ./fastlane/travis.sh
