desc "Runs tests on the primary platforms and configurations"
lane :test do
    verify(
        scheme: "BaseViewControllerSwift iOS"
    )
    verify(
        scheme: "BaseViewControllerSwift tvOS"
    )
    verify_demo
    pod_lib_lint
end

desc "Runs unit tests"
lane :verify do |options|
    scheme = options[:scheme]
    destination = options[:destination]
    sdk = options[:sdk]
    output_directory = "fastlane/test_output/" + scheme + "/"
    opts = {
        :workspace => 'BaseViewControllerSwift.xcworkspace',
        :scheme => scheme,
        :destination => destination,
        :sdk => sdk,
        :code_coverage => true,
        :xcargs => "ONLY_ACTIVE_ARCH=YES",
        :output_directory => output_directory,
        :clean => true
    }
    scan(opts)
    upload_cov
end

desc "Build demo app"
lane :verify_demo do
    scheme = "iOS Example"
    output_directory = "fastlane/test_output/" + scheme + "/"
    xcodebuild(
        workspace: "BaseViewControllerSwift.xcworkspace",
        scheme: scheme,
        sdk: "iphonesimulator10.2",
        output_directory: output_directory,
        clean: true,
        build: true
    )
end

desc "Upload code coverage reports (if running on CI)"
lane :upload_cov do
    if is_ci?
        sh "bash ./codecov.sh"
    else
        say "No need to upload code coverage. Not running from CI."
    end
end

desc "Updates the GitHub Pages documentation"
lane :update_docs do
    jazzy
end
